---
title: "MGMT 47400: Predictive Analytics"
subtitle: "Mitch. Daniels School of Business, Purdue University"
---

<!--- # IMPORTANT REFERENCE: https://www.youtube.com/watch?v=uimdXPZc40I&list=PLkrJrLs7xfbXcEKhTCKRSr2VXH4yiBeXo&index=4 --->

<br>

<center>

*IMPORTANT*

*This document does not replace the official information in the course brightspace page*

</center>

<br>

## Course Description

XXX This course is designed to introduce students to basic data analysis techniques. Coverage will include the application of probability distributions such as the normal, the $t$, and the binomial; sampling distributions, basic statistical inference methods, analysis of variance, applied linear regression techniques, logistic regression time series analysis, statistical quality control, and decision analysis.

**Course Website**: [https://davi-moreira.github.io/2025F_business_statistics_purdue_MGMT305](https://davi-moreira.github.io/2025F_business_statistics_purdue_MGMT305){target="_blank"}

### Instructor: [Professor Davi Moreira](https://davi-moreira.github.io)

-   Email: [dmoreira\@purdue.edu](mailto:dmoreira@purdue.edu)
-   Virtual Office hours: *Zoom link in your Course Brightspace Page*
-   Individual Appointments: *Book time with me through the link in the course syllabus on your Course Brightspace Page or by appointment.*

## Learning Outcomes

By the end of this course, students will be able to:

1.  Understand the basic statistical principles and their applications in the area of management and business.
2.  Understand fundamental issues in business and management.
3.  Describe and use the commonly used statistical techniques for analyzing business data.
4.  Understand the impacts of recent developments in big data and AI in business and management.
5.  Be proficient in using Excel to carry out statistical and analytics methods covered in the course.

## Objective

Our main goal is to instill the basic quantitative and data analysis skills needed by managers in modern business, where Business Analytics and Data Science have become important. These skills will help managers to understand and carry out data-based decision making, risk assessments, and policy making and to work effectively with data analysis teams to improve all aspects of business performance.

Modern data analysis is done using computers and various types of sophisticated software. Therefore, to most effectively introduce management candidates to its techniques, we will also emphasize software applications (with Microsoft Excel, R, or Python) in this course.

### Course Materials

The following are learning materials:

1.  Text book: Anderson, Sweeney, Williams, Camn, Cochran, Fry, and Ohlmann: Modern Business Statistics with Microsoft Excel, 7th edition, 2018, Cengage Learning, Inc. (Required) This text is also used in STAT 30301.
2.  Handouts: Lecture Slides and Supplementary Materials. (Posted in this page and on Brightspace: Brightspace -\> Content -\> Table of Contents -\> ….)

### Course Infra-structure

**Brightspace:** The Course Brightspace Page <https://purdue.brightspace.com/> should be checked on a regular basis for announcements and course material.

**Software:** Microsoft Excel will be used for in-class demonstrations and instruction. The main tool is Data Analysis under Tools. If you don’t see this tool, follow the following steps to add in:

-   File -\> Options -\> Add-ins -\> Select Analysis ToolPak and Analysis ToolPak-VBA (also select StatTools 7.5, if available) -\> Go -\> Data -\> Data Analysis (to conduct analyses)

**Course Website:** This class website will be used throughout the course, but it does not replace the Course Brightspace Page.
